// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {main} from '../models';
import {context} from '../models';

export function AddTask(arg1:string,arg2:time.Time):Promise<main.Task>;

export function GetAllTasks():Promise<Array<main.Task>>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleTask(arg1:number):Promise<main.Task>;
